name: DepMount
version: '${version}'
main: deponn.depmount.DepMount

commands: #自作プラグインのコマンドを宣言
  /mountain:
    description: ラピスラズリブロックの点の補間により山を作成します。
    usage: //mountain [-a|--all:空気以外も書き換え] [-b|--border:境界を作成] [-n|--num:補完の頂点数]
    permission: mountain

permissions:
  mountain:
    description: op only
    default: op